apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pve-node-3-home-arpa
  namespace: cert-manager
spec:
  secretName: pve-node-3-home-arpa-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - pve-node-3.home.arpa