apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-home-arpa
  namespace: homepage
spec:
  secretName: homepage-home-arpa-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - homepage.home.arpa