apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

  - ../infrastructure/networking.yaml
  - ../infrastructure/ingress.yaml
  - ../infrastructure/storage.yaml
  - ../infrastructure/monitoring.yaml

  - ../applications/apps.yaml

